In [3]:
from scipy.optimize import curve_fit
import numpy as np

In [12]:
curve_fit(lambda x, a, b:  (a + (0.1 * b/5) * x ** 2)**2, np.array([3,5,7,9,11]), [0.06598, 0.06821, 0.07159, 0.07718 ,0.08536])

(array([0.25308416, 0.01581419]),
 array([[ 7.33398896e-07, -4.16026787e-07],
        [-4.16026787e-07,  3.42179789e-07]]))

In [7]:
curve_fit(lambda x, a, b, c:  a ** 2+ (b/5) * x ** 2 + c/25 * x ** 4, np.array([3,5,7,9,11]), [0.06598, 0.06821, 0.07159, 0.07718 ,0.08536])

(array([2.54876645e-01, 5.73543647e-04, 1.11249849e-05]),
 array([[ 4.51510849e-08, -3.90316344e-09,  1.27378336e-10],
        [-3.90316344e-09,  4.55509400e-10, -1.64710448e-11],
        [ 1.27378336e-10, -1.64710448e-11,  6.31650798e-13]]))