In [64]:
from scipy.optimize import curve_fit
import numpy as np

gen_val = {
    "Signal_500": {
        "g": np.array([5, 7, 9, 11, 13]),
        "width_tg": [0.1817, 0.3563, 0.5890, 0.8798, 1.2289],
        "xsec_TT": [2.325581e+00, 2.355341e+00, 2.431030e+00, 2.516361e+00, 2.638057e+00],
    },
    "Signal_750": {
        "g": np.array([5, 7, 9, 11, 13]),
        "width_tg": [0.7612, 1.4921, 2.4665, 3.6846, 5.1463],
        "xsec_TT": [2.184231e-01, 2.259208e-01, 2.364962e-01, 2.537361e-01, 2.771376e-01],
    },
    "Signal_1000": {
        "g": np.array([5, 7, 9, 11, 13]),
        "width_tg": [1.939, 3.8009, 6.2831, 9.3859, 13.1092],
        "xsec_TT": [3.389237e-02, 3.563196e-02, 3.849664e-02, 4.252330e-02, 4.853439e-02],
    },
    "Signal_1250": {
        "g": np.array([5, 7, 9, 11, 13]),
        "width_tg": [3.913, 7.6707, 12.6802, 18.942, 26.456],
        "xsec_TT": [6.981026e-03, 7.439504e-03, 8.162695e-03, 9.325584e-03, 1.099415e-02],
    },
    "Signal_1500": {
        "g": np.array([5, 7, 9, 11, 13]),
        "width_tg": [6.883, 13.49100, 22.3014, 33.314, 46.530],
        "xsec_TT": [1.657904e-03, 1.778181e-03, 2.006442e-03, 2.359005e-03, 2.877716e-03],
    },
    "Signal_1750": {
        "g": np.array([5, 7, 9, 11, 13]),
        "width_tg": [11.0465, 21.6511, 35.7907, 53.4652, 74.6745],
        "xsec_TT": [4.340251e-04, 4.745353e-04, 5.391757e-04, 6.492909e-04, 8.134738e-04],
    },
    "Signal_2000": {
        "g": np.array([5, 7, 9, 11, 13]),
        "width_tg": [16.602, 32.5411, 53.792, 80.356, 112.233],
        "xsec_TT": [1.207999e-04, 1.310072e-04, 1.518117e-04, 1.855338e-04, 2.372002e-04],
    },
    "Signal_2250": {
        "g": np.array([5, 7, 9, 11, 13]),
        "width_tg": [23.7503, 46.5507, 76.951, 114.951, 160.552],
        "xsec_TT": [3.454268e-05, 3.757359e-05, 4.363370e-05, 5.329513e-05, 6.961889e-05],
    },
    "Signal_2500": {
        "g": np.array([5, 7, 9, 11, 13]),
        "width_tg": [32.6886, 64.0697, 105.911, 158.213, 220.975],
        "xsec_TT": [1.017082e-05, 1.108402e-05, 1.277048e-05, 1.576809e-05, 2.057444e-05],
    },
    "Signal_2750": {
        "g": np.array([5, 7, 9, 11, 13]),
        "width_tg": [43.6164, 85.4882, 141.317, 211.103, 294.847],
        "xsec_TT": [3.027667e-06, 3.277126e-06, 3.737304e-06, 4.596437e-06, 5.970259e-06],
    },
    "Signal_3000": {
        "g": np.array([5, 7, 9, 11, 13]),
        "width_tg": [56.732, 111.1959, 183.8136, 274.585, 383.512],
        "xsec_TT": [9.198671e-07, 9.839057e-07, 1.107198e-06, 1.332289e-06, 1.711181e-06],
    },
}


def br_prefactor(mass):
    g = gen_val[f"Signal_{mass}"]["g"]
    width = gen_val[f"Signal_{mass}"]["width_tg"]
    return curve_fit(lambda x, a:  a * x ** 2, 0.1 * g/5, width)

def xsec_factors(mass):
    g = gen_val[f"Signal_{mass}"]["g"]
    xsec = gen_val[f"Signal_{mass}"]["xsec_TT"]
    return curve_fit(lambda x, a, b, c:  a + b * x ** 2 + c * x ** 4, (g*0.1/5), xsec)

for m in [500, 750, 1000, 1250, 1500, 1750, 2000, 2250, 2500, 2750, 3000]:
    print("br factor:", br_prefactor(m))
    print("xsec factors:", xsec_factors(m)[0])
    print("error xsec factors:","\n", xsec_factors(m)[1],"\n")

br factor: (array([18.17850783]), array([[3.01019204e-07]]))
xsec factors: [ 2.28208015  3.70973931 23.16245342]
error xsec factors: 
 [[ 1.48778991e-04 -8.53367300e-03  9.80876046e-02]
 [-8.53367300e-03  5.74742517e-01 -7.06063392e+00]
 [ 9.80876046e-02 -7.06063392e+00  9.07332599e+01]] 

br factor: (array([76.12810908]), array([[3.21316664e-07]]))
xsec factors: [0.21208729 0.58296298 5.62498052]
error xsec factors: 
 [[ 3.91858687e-07 -2.24762543e-05  2.58346206e-04]
 [-2.24762543e-05  1.51377506e-03 -1.85965223e-02]
 [ 2.58346206e-04 -1.85965223e-02  2.38976154e-01]] 

br factor: (array([193.92292428]), array([[1.58971736e-06]]))
xsec factors: [0.03233369 0.14119539 1.45359946]
error xsec factors: 
 [[ 1.01163422e-08 -5.80253846e-07  6.66954519e-06]
 [-5.80253846e-07  3.90800844e-05 -4.80093598e-04]
 [ 6.66954519e-06 -4.80093598e-04  6.16948298e-03]] 

br factor: (array([391.3614342]), array([[1.17842576e-05]]))
xsec factors: [0.00659803 0.03358636 0.46581976]
error xsec factors: 
 

In [40]:
br_prefactor(3000)

(array([5673.2517049]), array([[1.58487515e-05]]))

In [41]:
xsec_factors(3000)

(array([8.88256955e-07, 1.75890679e-06, 1.53923002e-04]),
 array([[ 1.30850013e-17, -7.50530315e-16,  8.62673179e-15],
        [-7.50530315e-16,  5.05481939e-14, -6.20977605e-13],
        [ 8.62673179e-15, -6.20977605e-13,  7.97992263e-12]]))

In [16]:
br_prefactor(np.array([3,5,7,9,11]), [0.06598, 0.06821, 0.07159, 0.07718 ,0.08536])

(array([0.00092094]), array([[6.94906202e-08]]))

In [17]:
curve_fit(lambda x, a, b:  (a + (b) * x ** 2)**2, np.array([0.1 * 3/5,0.1 * 5/5,0.1 * 7/5,0.1 * 9/5,0.1 * 11/5]), [0.06598, 0.06821, 0.07159, 0.07718 ,0.08536])

(array([0.25308416, 0.7907094 ]),
 array([[ 7.33398584e-07, -2.08013364e-05],
        [-2.08013364e-05,  8.55449684e-04]]))

In [66]:
curve_fit(lambda x, a, b, c:  a + b * x ** 2 + c * x ** 4, np.array([0.1 * 5/5,0.1 * 7/5,0.1 * 9/5,0.1 * 11/5,0.1 * 13/5]), [0.03394, 0.03596, 0.03845, 0.04254 ,0.04837])

(array([0.03246587, 0.14271016, 1.36489614]),
 array([[ 6.18629354e-08, -3.54833893e-06,  4.07852661e-05],
        [-3.54833893e-06,  2.38980613e-04, -2.93584501e-03],
        [ 4.07852661e-05, -2.93584501e-03,  3.77273252e-02]]))

In [20]:
[3,5,7,9,11]/5 *0.1

TypeError: unsupported operand type(s) for /: 'list' and 'int'